# Data splitting
TEST_SIZE = 0.2
SPLIT_RANDOM_STATE = 11


# General
MODEL_RANDOM_STATE = 42


# Logistic Regression
LOGREG_MAX_ITER = 100


# Random Forest
RF_N_ESTIMATORS = 100
RF_MAX_DEPTH = None
RF_CLASS_WEIGHT = None


# XGBoost
XGB_N_ESTIMATORS = 300
XGB_MAX_DEPTH = 4
XGB_LEARNING_RATE = 0.05
XGB_SUBSAMPLE = 0.8
XGB_COLSAMPLE_BYTREE = 0.8
XGB_MIN_CHILD_WEIGHT = 5
XGB_GAMMA = 0.3
XGB_REG_ALPHA = 0.1
XGB_REG_LAMBDA = 1

XGB_EVAL_METRIC = "logloss"
XGB_THRESHOLD = 0.60

